.github/workflows/java8-build.yml

Add Github Actions to flink-ml for every push and pull request.

[FLINK-22013] Add Github Actions to flink-ml for every push and pull request

---

flink-ml-core/pom.xml
flink-ml-iteration/pom.xml
flink-ml-lib/pom.xml
flink-ml-tests/pom.xml
flink-ml-uber/pom.xml

This PR cherry-picks https://github.com/apache/flink-ml/pull/49 to master.

[hotfix] Add scala version as suffix of all modules

---

flink-ml-core/pom.xml
flink-ml-core/src/main/java/org/apache/flink/ml/util/ReadWriteUtils.java
flink-ml-core/src/test/java/org/apache/flink/ml/util/ReadWriteUtilsTest.java

[FLINK-26404](https://issues.apache.org/jira/browse/FLINK-26404) Flink-ML should support non-local file systems

[FLINK-26404] support non-local file systems

---

flink-ml-core/src/main/java/org/apache/flink/ml/common/datastream/DataStreamUtils.java
flink-ml-core/src/test/java/org/apache/flink/ml/common/datastream/DataStreamUtilsTest.java
flink-ml-lib/src/main/java/org/apache/flink/ml/feature/stringindexer/IndexToStringModel.java
flink-ml-lib/src/main/java/org/apache/flink/ml/feature/stringindexer/IndexToStringModelParams.java
flink-ml-lib/src/main/java/org/apache/flink/ml/feature/stringindexer/StringIndexer.java
flink-ml-lib/src/main/java/org/apache/flink/ml/feature/stringindexer/StringIndexerModel.java
flink-ml-lib/src/main/java/org/apache/flink/ml/feature/stringindexer/StringIndexerModelData.java
flink-ml-lib/src/main/java/org/apache/flink/ml/feature/stringindexer/StringIndexerModelParams.java
flink-ml-lib/src/main/java/org/apache/flink/ml/feature/stringindexer/StringIndexerParams.java
flink-ml-lib/src/test/java/org/apache/flink/ml/feature/stringindexer/IndexToStringModelTest.java
flink-ml-lib/src/test/java/org/apache/flink/ml/feature/stringindexer/StringIndexerTest.java

- Add Transformer and Estimator of StringIndexer in FlinkML.
- Add StringIndexer.
- Add StringIndexerModel.
- Add IndexToStringModel.

[FLINK-25527] Add Transformer and Estimator for StringIndexer

---

flink-ml-core/src/main/java/org/apache/flink/ml/common/datastream/DataStreamUtils.java
flink-ml-core/src/main/java/org/apache/flink/ml/linalg/BLAS.java
flink-ml-core/src/test/java/org/apache/flink/ml/common/datastream/DataStreamUtilsTest.java
flink-ml-core/src/test/java/org/apache/flink/ml/linalg/BLASTest.java
flink-ml-lib/src/main/java/org/apache/flink/ml/classification/logisticregression/LogisticRegression.java
flink-ml-lib/src/main/java/org/apache/flink/ml/classification/logisticregression/LogisticRegressionModel.java
flink-ml-lib/src/main/java/org/apache/flink/ml/classification/logisticregression/LogisticRegressionModelData.java
flink-ml-lib/src/main/java/org/apache/flink/ml/classification/logisticregression/OnlineLogisticRegression.java
flink-ml-lib/src/main/java/org/apache/flink/ml/classification/logisticregression/OnlineLogisticRegressionModel.java
flink-ml-lib/src/main/java/org/apache/flink/ml/classification/logisticregression/OnlineLogisticRegressionModelParams.java
flink-ml-lib/src/main/java/org/apache/flink/ml/classification/logisticregression/OnlineLogisticRegressionParams.java
flink-ml-lib/src/main/java/org/apache/flink/ml/clustering/kmeans/OnlineKMeans.java
flink-ml-lib/src/test/java/org/apache/flink/ml/classification/LogisticRegressionTest.java
flink-ml-lib/src/test/java/org/apache/flink/ml/classification/OnlineLogisticRegressionTest.java
flink-ml-lib/src/test/java/org/apache/flink/ml/feature/MinMaxScalerTest.java
flink-ml-lib/src/test/java/org/apache/flink/ml/util/TestUtils.java
flink-ml-python/pyflink/ml/lib/classification/logisticregression.py
flink-ml-python/pyflink/ml/lib/classification/tests/test_logisticregression.py

Add Transformer and Estimator of OnlineLogisticRegression

[FLINK-27170] Add Transformer and Estimator for OnlineLogisticRegression

---

flink-ml-iteration/src/main/java/org/apache/flink/iteration/broadcast/RecordWriterBroadcastOutput.java

This PR reduces Flink ML iteration's latency by enforcing flush at each iteration epoch watermark.

[FLINK-27096] Flush buffer at epoch watermark

---

flink-ml-examples/src/main/java/org/apache/flink/ml/examples/feature/RegexTokenizerExample.java
flink-ml-lib/src/main/java/org/apache/flink/ml/feature/regextokenizer/RegexTokenizer.java
flink-ml-lib/src/main/java/org/apache/flink/ml/feature/regextokenizer/RegexTokenizerParams.java
flink-ml-lib/src/test/java/org/apache/flink/ml/feature/RegexTokenizerTest.java
flink-ml-python/pyflink/examples/ml/feature/regextokenizer_example.py
flink-ml-python/pyflink/ml/lib/feature/regextokenizer.py
flink-ml-python/pyflink/ml/lib/feature/tests/test_regextokenizer.py

This PR adds Transformer for RegexTokenizer to Flink ML.

[FLINK-28502] Add Transformer for RegexTokenizer

---

docs/content/docs/try-flink-ml/build-your-own-project.md
flink-ml-python/dev/dev-requirements.txt
flink-ml-python/setup.py
pom.xml

This PR updates Flink ML's Flink dependency to Flink 1.15.1

[FLINK-28673] Migrate Flink ML to Flink 1.15.1

---

flink-ml-lib/src/main/java/org/apache/flink/ml/feature/onehotencoder/OneHotEncoder.java

This PR fixes the NullPointerException that might be generated during OneHotEncoder's checkpoint process.

[FLINK-28684] Fix OneHotEncoder NPE during checkpoint

---

flink-ml-examples/src/main/java/org/apache/flink/ml/examples/feature/FeatureHasherExample.java
flink-ml-lib/src/main/java/org/apache/flink/ml/common/param/HasCategoricalCols.java
flink-ml-lib/src/main/java/org/apache/flink/ml/common/param/HasNumFeatures.java
flink-ml-lib/src/main/java/org/apache/flink/ml/feature/featurehasher/FeatureHasher.java
flink-ml-lib/src/main/java/org/apache/flink/ml/feature/featurehasher/FeatureHasherParams.java
flink-ml-lib/src/test/java/org/apache/flink/ml/feature/FeatureHasherTest.java
flink-ml-python/pyflink/examples/ml/feature/featurehasher_example.py
flink-ml-python/pyflink/ml/lib/feature/featurehasher.py
flink-ml-python/pyflink/ml/lib/feature/tests/test_feature_hasher.py
flink-ml-python/pyflink/ml/lib/param.py

Add Transformer for FeatureHasher.
Add Transformer for FeatureHasher in Flink ML (Java & Python).
Add unit test for FeatureHasher (Java & Python)
Add example code for FeatureHasher (Java&Python)

[FLINK-28601] Add Transformer for FeatureHasher

---

flink-ml-iteration/src/main/java/org/apache/flink/iteration/operator/HeadOperator.java

Improve the performance of Flink ML iteration mechanism by reducing the overhead on HeadOperator
The performance improvement brought by this PR on the execution time of unit tests of algorithms with iterations are as follows.
|                        | Before this PR[1] | After this PR [2] |
| ---------------------- | ----------------- | ----------------- |
| LinearSVCTest          | 34.597 s          | 15.623 s          |
| LogisticRegressionTest | 48.325 s          | 24.649 s          |
| KMeansTest             | 32.816 s          | 29.967 s          |
| LinearRegressionTest   | 49.92 s           | 33.991 s          |
[1] https://github.com/apache/flink-ml/runs/7892649470?check_suite_focus=true
[2] https://github.com/apache/flink-ml/runs/7916115762?check_suite_focus=true
- Add …

[FLINK-29043] Reduce HeadOperator overhead

---

docs/content/docs/operators/clustering/agglomerativeclustering.md
docs/content/docs/operators/feature/kbinsdiscretizer.md
docs/content/docs/operators/feature/regextokenizer.md
docs/content/docs/operators/feature/tokenizer.md
docs/content/docs/operators/feature/vectorindexer.md
flink-ml-python/pyflink/examples/ml/feature/hashingtf_example.py
flink-ml-python/pyflink/examples/ml/feature/indextostringmodel_example.py
flink-ml-python/pyflink/examples/ml/feature/kbinsdiscreteizer_example.py
flink-ml-python/pyflink/examples/ml/feature/regextokenizer_example.py
flink-ml-python/pyflink/examples/ml/feature/tokenizer_example.py
flink-ml-python/pyflink/examples/ml/feature/vectorindexer_example.py

This PR adds documents for four feature engineering algorithms.

[FLINK-29175] Add documents for KBinsDiscretizer, RegexTokenizer, Tokenizer and VectorIndexer

---

.github/PULL_REQUEST_TEMPLATE.md

Add Pull Request Template for Flink ML
- Add Pull Request Template for Flink ML

[FLINK-29424] Add Pull Request Template

---

docs/content/docs/operators/feature/imputer.md
flink-ml-core/src/main/java/org/apache/flink/ml/param/DoubleParam.java
flink-ml-core/src/main/java/org/apache/flink/ml/param/FloatParam.java
flink-ml-core/src/test/java/org/apache/flink/ml/api/StageTest.java
flink-ml-examples/src/main/java/org/apache/flink/ml/examples/feature/ImputerExample.java
flink-ml-lib/src/main/java/org/apache/flink/ml/common/param/HasRelativeError.java
flink-ml-lib/src/main/java/org/apache/flink/ml/common/util/QuantileSummary.java
flink-ml-lib/src/main/java/org/apache/flink/ml/feature/imputer/Imputer.java
flink-ml-lib/src/main/java/org/apache/flink/ml/feature/imputer/ImputerModel.java
flink-ml-lib/src/main/java/org/apache/flink/ml/feature/imputer/ImputerModelData.java
flink-ml-lib/src/main/java/org/apache/flink/ml/feature/imputer/ImputerModelParams.java
flink-ml-lib/src/main/java/org/apache/flink/ml/feature/imputer/ImputerParams.java
flink-ml-lib/src/test/java/org/apache/flink/ml/common/util/QuantileSummaryTest.java
flink-ml-lib/src/test/java/org/apache/flink/ml/feature/ImputerTest.java
flink-ml-python/pyflink/examples/ml/feature/imputer_example.py
flink-ml-python/pyflink/ml/core/tests/test_param.py
flink-ml-python/pyflink/ml/lib/feature/imputer.py
flink-ml-python/pyflink/ml/lib/feature/tests/test_imputer.py
flink-ml-python/pyflink/ml/lib/param.py

Add Estimator and Transformer for Imputer
- Adds Transformer and Estimator implementation of Imputer in Java and Python.
- Adds `HasRelativeError` as a common param interface because other algorithms like RobustScaler also needs this param.
- Adds examples of Imputer.
- Add documentations of Imputer .

[FLINK-29598] Add Estimator and Transformer for Imputer

---

docs/content/docs/operators/feature/randomsplitter.md
flink-ml-examples/src/main/java/org/apache/flink/ml/examples/feature/RandomSplitterExample.java
flink-ml-lib/src/main/java/org/apache/flink/ml/feature/randomsplitter/RandomSplitter.java
flink-ml-lib/src/main/java/org/apache/flink/ml/feature/randomsplitter/RandomSplitterParams.java
flink-ml-lib/src/test/java/org/apache/flink/ml/feature/RandomSplitterTest.java
flink-ml-python/pyflink/examples/ml/feature/randomsplitter_example.py
flink-ml-python/pyflink/ml/lib/feature/normalizer.py
flink-ml-python/pyflink/ml/lib/feature/randomsplitter.py
flink-ml-python/pyflink/ml/lib/feature/tests/test_normalizer.py
flink-ml-python/pyflink/ml/lib/feature/tests/test_randomsplitter.py

This pull request Add AlgoOperator for Splitter.
- Adds Add AlgoOperator for Splitter in Java and Python
- Adds examples and documentations of Splitter
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes)

[FLINK-29434] Add AlgoOperator for Splitter

---

docs/content/docs/operators/feature/robustscaler.md
flink-ml-examples/src/main/java/org/apache/flink/ml/examples/feature/RobustScalerExample.java
flink-ml-lib/src/main/java/org/apache/flink/ml/common/param/HasRelativeError.java
flink-ml-lib/src/main/java/org/apache/flink/ml/feature/robustscaler/RobustScaler.java
flink-ml-lib/src/main/java/org/apache/flink/ml/feature/robustscaler/RobustScalerModel.java
flink-ml-lib/src/main/java/org/apache/flink/ml/feature/robustscaler/RobustScalerModelData.java
flink-ml-lib/src/main/java/org/apache/flink/ml/feature/robustscaler/RobustScalerModelParams.java
flink-ml-lib/src/main/java/org/apache/flink/ml/feature/robustscaler/RobustScalerParams.java
flink-ml-lib/src/test/java/org/apache/flink/ml/feature/ImputerTest.java
flink-ml-lib/src/test/java/org/apache/flink/ml/feature/RobustScalerTest.java
flink-ml-lib/src/test/java/org/apache/flink/ml/feature/VarianceThresholdSelectorTest.java
flink-ml-python/pyflink/examples/ml/feature/robustscaler_example.py
flink-ml-python/pyflink/ml/lib/feature/robustscaler.py
flink-ml-python/pyflink/ml/lib/feature/tests/test_robustscaler.py

Add Estimator and Transformer for RobustScaler.
- Adds Transformer and Estimator implementation of RobustScaler in Java and Python
- Adds examples and documentation of RobustScaler

[FLINK-29592] Add Estimator and Transformer for RobustScaler

---

docs/content/docs/operators/feature/countvectorizer.md
flink-ml-examples/src/main/java/org/apache/flink/ml/examples/feature/CountVectorizerExample.java
flink-ml-lib/src/main/java/org/apache/flink/ml/feature/countvectorizer/CountVectorizer.java
flink-ml-lib/src/main/java/org/apache/flink/ml/feature/countvectorizer/CountVectorizerModel.java
flink-ml-lib/src/main/java/org/apache/flink/ml/feature/countvectorizer/CountVectorizerModelData.java
flink-ml-lib/src/main/java/org/apache/flink/ml/feature/countvectorizer/CountVectorizerModelParams.java
flink-ml-lib/src/main/java/org/apache/flink/ml/feature/countvectorizer/CountVectorizerParams.java
flink-ml-lib/src/test/java/org/apache/flink/ml/feature/CountVectorizerTest.java
flink-ml-python/pyflink/examples/ml/feature/countvectorizer_example.py
flink-ml-python/pyflink/ml/lib/feature/countvectorizer.py
flink-ml-python/pyflink/ml/lib/feature/tests/test_countvectorizer.py

Add Estimator and Transformer for CountVectorizer.
- Adds Transformer and Estimator implementation of CountVectorizer in Java and Python.
- Adds examples and documentation of CountVectorizer.

[FLINK-29604] Add Estimator and Transformer for CountVectorizer

---

flink-ml-lib/src/main/java/org/apache/flink/ml/common/param/HasFlatten.java
flink-ml-lib/src/main/java/org/apache/flink/ml/stats/anovatest/ANOVATest.java
flink-ml-lib/src/main/java/org/apache/flink/ml/stats/anovatest/ANOVATestParams.java
flink-ml-lib/src/main/java/org/apache/flink/ml/stats/chisqtest/ChiSqTest.java
flink-ml-lib/src/test/java/org/apache/flink/ml/stats/ANOVATestTest.java
flink-ml-python/pyflink/ml/core/tests/test_param.py
flink-ml-python/pyflink/ml/lib/param.py
flink-ml-python/pyflink/ml/lib/stats/chisqtest.py
flink-ml-python/pyflink/ml/lib/tests/test_ml_lib_completeness.py

Add Transformer for ANOVATest. It is an internal algorithm that is used in Univariate Feature Selector, so it has only Java implementation.
- Adds shared parameter `HaSFlatten`
- Adds Transformer implementation of ANOVATest in Java.
- Dependencies (does it add or upgrade a dependency): ( no)

[FLINK-30159] Add Transformer for ANOVATest

---

flink-ml-lib/src/main/java/org/apache/flink/ml/stats/fvaluetest/FValueTest.java
flink-ml-lib/src/main/java/org/apache/flink/ml/stats/fvaluetest/FValueTestParams.java
flink-ml-lib/src/test/java/org/apache/flink/ml/stats/FValueTestTest.java
flink-ml-python/pyflink/ml/lib/tests/test_ml_lib_completeness.py

Add Transformer for FValueTest. This is an internal algorithm so only java implementation is needed.
- Adds Transformer implementation and tests of FValueTest in Java.

[FLINK-30160] Add Transformer for FValueTest

---

.github/workflows/python-checks.yml
README.md

Add Python quickstart link in README
Added Python quickstart link in README

[hotfix] Add Python quickstart link in README

---

.github/workflows/java-tests.yml
.github/workflows/python-tests.yml

Improve nightly build Github actions.
This PR made the following changes:
- Skipped triggering CI and nightly build on forked repo.
- Added nightly build for Java tests for consistency with python tests
- Renamed Github actions for Python and Java tests for consistency.
- If yes, how is the feature documented? not applicable.

[hotfix] Improve nightly build Github actions

---

docs/content/docs/operators/feature/univariatefeatureselector.md
flink-ml-examples/src/main/java/org/apache/flink/ml/examples/feature/UnivariateFeatureSelectorExample.java
flink-ml-lib/src/main/java/org/apache/flink/ml/common/util/VectorUtils.java
flink-ml-lib/src/main/java/org/apache/flink/ml/feature/univariatefeatureselector/UnivariateFeatureSelector.java
flink-ml-lib/src/main/java/org/apache/flink/ml/feature/univariatefeatureselector/UnivariateFeatureSelectorModel.java
flink-ml-lib/src/main/java/org/apache/flink/ml/feature/univariatefeatureselector/UnivariateFeatureSelectorModelData.java
flink-ml-lib/src/main/java/org/apache/flink/ml/feature/univariatefeatureselector/UnivariateFeatureSelectorModelParams.java
flink-ml-lib/src/main/java/org/apache/flink/ml/feature/univariatefeatureselector/UnivariateFeatureSelectorParams.java
flink-ml-lib/src/main/java/org/apache/flink/ml/feature/variancethresholdselector/VarianceThresholdSelector.java
flink-ml-lib/src/test/java/org/apache/flink/ml/common/util/VectorUtilsTest.java
flink-ml-lib/src/test/java/org/apache/flink/ml/feature/UnivariateFeatureSelectorTest.java
flink-ml-lib/src/test/java/org/apache/flink/ml/feature/VarianceThresholdSelectorTest.java
flink-ml-python/pyflink/examples/ml/feature/univariatefeatureselector_example.py
flink-ml-python/pyflink/ml/lib/feature/tests/test_univariatefeatureselector.py
flink-ml-python/pyflink/ml/lib/feature/univariatefeatureselector.py

Add Estimator and Transformer for UnivariateFeatureSelector
- Adds Transformer and Estimator implementation of UnivariateFeatureSelector in Java and Python
- Adds examples and documentation of UnivariateFeatureSelector
- VarianceThresholdSelectorModel supports sparse vectors as outputs.

[FLINK-29601] Add Estimator and Transformer for UnivariateFeatureSelector

---

docs/content/docs/operators/recommendation/_index.md
docs/content/docs/operators/recommendation/swing.md
flink-ml-examples/src/main/java/org/apache/flink/ml/examples/recommendation/SwingExample.java
flink-ml-lib/src/main/java/org/apache/flink/ml/recommendation/swing/Swing.java
flink-ml-lib/src/main/java/org/apache/flink/ml/recommendation/swing/SwingParams.java
flink-ml-lib/src/test/java/org/apache/flink/ml/recommendation/SwingTest.java
flink-ml-python/pyflink/examples/ml/recommendation/swing_example.py
flink-ml-python/pyflink/ml/recommendation/__init__.py
flink-ml-python/pyflink/ml/recommendation/common.py
flink-ml-python/pyflink/ml/recommendation/swing.py
flink-ml-python/pyflink/ml/recommendation/tests/__init__.py
flink-ml-python/pyflink/ml/recommendation/tests/test_swing.py
flink-ml-python/setup.py

* This pull request adds the implementation of Swing recommendation algorithm.
- Adds AlgoOperator implementation of Swing recommendation algorithm in Java and Python
- Adds examples and documentations of Swing in Java and Python
- Does this pull request introduce a new feature? yes
- If yes, how is the feature documented? docs / JavaDocs

[FLINK-30451] Add AlgoOperator for Swing

---

.github/workflows/java-tests.yml
.github/workflows/python-tests.yml

Supports triggering CI manually.
- Adds a workflow dispatch to trigger CI manually.

[FLINK-31948] Supports triggering CI manually
