apache/flink-ml

- flink-ml-examples/examples-batch/pom.xml
- flink-ml-examples/examples-batch/src/main/java/org/apache/flink/examples/java/ml/LinearRegression.java
- flink-ml-examples/examples-batch/src/main/java/org/apache/flink/examples/java/ml/util/LinearRegressionData.java
- flink-ml-examples/examples-batch/src/main/java/org/apache/flink/examples/java/ml/util/LinearRegressionDataGenerator.java
- flink-ml-examples/examples-batch/src/main/scala/org/apache/flink/examples/scala/ml/LinearRegression.scala
- flink-ml-examples/examples-streaming/pom.xml
- flink-ml-examples/examples-streaming/src/main/java/org/apache/flink/streaming/examples/ml/IncrementalLearningSkeleton.java
- flink-ml-examples/examples-streaming/src/main/java/org/apache/flink/streaming/examples/ml/util/IncrementalLearningSkeletonData.java
- flink-ml-examples/examples-streaming/src/main/scala/org/apache/flink/streaming/scala/examples/ml/IncrementalLearningSkeleton.scala
- flink-ml-examples/examples-streaming/src/test/java/org/apache/flink/streaming/test/StreamingExamplesITCase.java
- flink-ml-examples/examples-streaming/src/test/scala/org/apache/flink/streaming/scala/examples/StreamingExamplesITCase.scala
- flink-ml-examples/pom.xml
- pom.xml
- tools/maven/scalastyle-config.xml
Move ML examples from flink/flink-examples to the flink-ml repo.
- Updated the root pom.xml to include log4j dependency and scalastyle-maven-plugin
- Added modules and files under the `flink-ml-examples` directory. These files are mostly copied/pasted from flink repo without any change.
- Added StreamingExamplesITCase.java and StreamingExamplesITCase.scala.
- Passed `maven clean install`, which includes unit tests and integration tests (e.g. `StreamingExamplesITCase`)
- Compared the jars generated by the `flink-ml-examples` modeule  with those jars generated by the flink/flink-examples module. Verified that the only difference is the non-ML related jars which does not exist in the flink-ml repo.
- Can successfully run examples with the following example command
`mvn compile exec:java …
> [FLINK-21976] Add Flink ML examples

- flink-ml-core/pom.xml
- flink-ml-iteration/pom.xml
- flink-ml-lib/pom.xml
- flink-ml-tests/pom.xml
- flink-ml-uber/pom.xml
This PR adds scala version as suffix of all flink-ml sub-modules.
> [hotfix] Add scala version as suffix of all modules

- docs/config.toml
- docs/content/_index.md
Fix version and branch info of docs in release 2.0
- Change version number from `2.0.0` to `2.0`
- Change references to Flink ML Github repo from master branch to branch `release-2.0`
N/A
- If yes, how is the feature documented? (N/A)
> [hotfix] Fix version and branch info of docs in release 2.0

- flink-ml-core/src/main/java/org/apache/flink/ml/api/Stage.java
- flink-ml-core/src/main/java/org/apache/flink/ml/common/broadcast/BroadcastContext.java
- flink-ml-core/src/main/java/org/apache/flink/ml/common/distance/EuclideanDistanceMeasure.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/clustering/kmeans/KMeans.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/clustering/kmeans/KMeansModel.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/clustering/kmeans/KMeansModelData.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/clustering/kmeans/KMeansModelParams.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/clustering/kmeans/OnlineKMeans.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/clustering/kmeans/OnlineKMeansModel.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/clustering/kmeans/OnlineKMeansParams.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/common/param/HasBatchStrategy.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/common/param/HasDecayFactor.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/clustering/KMeansTest.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/clustering/OnlineKMeansTest.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/util/InMemorySinkFunction.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/util/InMemorySourceFunction.java
This PR adds Estimator and Transformer for the Online KMeans operator.
Compared with the existing KMeans operator, Online KMeans allows to train KMeans model continuously from an unbounded train data stream. The corresponding Model operator also supports updating model data dynamically from a DataStream.
In order for Online KMeans to train incrementally based on offline KMeans's model, this PR modifies KMeans's model data format to add a weight property.
Besides, this PR also adds simple infrastructures needed to test online algorithms, which allows to control the order to consume train data and predict data, or to read metrics.
- Adds `OnlineKMeans`, `OnlineKMeansModel` and `OnlineKMeansParams` class to support Online KMeans algorithm. Also adds `OnlineKMeansTest` class to test these …
> [FLINK-26313] Add Transformer and Estimator of OnlineKMeans 

- README.md
This PR adds a link to Flink ML's document website in README.md. The added content is referenced from Flink repo's README.
> [FLINK-26100] Add link to document website in README

- flink-ml-lib/src/main/java/org/apache/flink/ml/common/param/HasOutputCol.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/vectorassembler/VectorAssembler.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/vectorassembler/VectorAssemblerParams.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/feature/VectorAssemblerTest.java
Add Transformer for VectorAssembler in FlinkML.
Add VectorAssembler.
Does this pull request introduce a new feature? (no)
> [FLINK-25616] Add Transformer for VectorAssembler

- flink-ml-core/src/main/java/org/apache/flink/ml/linalg/BLAS.java
- flink-ml-core/src/main/java/org/apache/flink/ml/linalg/DenseVector.java
- flink-ml-core/src/main/java/org/apache/flink/ml/linalg/SparseVector.java
- flink-ml-core/src/test/java/org/apache/flink/ml/linalg/BLASTest.java
- flink-ml-core/src/test/java/org/apache/flink/ml/linalg/DenseVectorTest.java
- flink-ml-core/src/test/java/org/apache/flink/ml/linalg/SparseVectorTest.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/common/param/HasInputCol.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/minmaxscaler/MinMaxScaler.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/minmaxscaler/MinMaxScalerModel.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/minmaxscaler/MinMaxScalerParams.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/standardscaler/StandardScaler.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/standardscaler/StandardScalerModel.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/standardscaler/StandardScalerModelData.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/standardscaler/StandardScalerParams.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/classification/KnnTest.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/classification/LogisticRegressionTest.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/classification/NaiveBayesTest.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/clustering/KMeansTest.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/feature/MinMaxScalerTest.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/feature/StandardScalerTest.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/feature/stringindexer/IndexToStringModelTest.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/feature/stringindexer/StringIndexerTest.java
- Add Transformer and Estimator of StandardScaler in FlinkML. Standardization is a common requirement for machine learning training because they may behave badly if the individual features of a input do not look like standard normally distributed data (e.g. Gaussian with 0 mean and unit variance).
- Add StandardScaler.
- Add StandardScalerModel.
- Add unit test for the proposed functionalities.
> [FLINK-26626] Add Transformer and Estimator for StandardScaler

- .github/workflows/java8-build.yml
Currently the Java 8 Build log from github action could contain 20000+ lines of logs with redundant information such as `Progress (1): 17/36 MB` [1]. This information is typically not useful for developers and make it hard to find the useful information from the github webpage.
This PR uses the `--no-transfer-progress` option to suppress the output of downloading messages [2].
The effective of this PR has been verified via the Java 8 Build log in this PR [3].
[1] https://github.com/apache/flink-ml/runs/6106425232?check_suite_focus=true
[2] https://stackoverflow.com/questions/21638697/disable-maven-download-progress-indication
[3] https://github.com/apache/flink-ml/runs/6144354382?check_suite_focus=true
> [hotfix] Suppress the output of downloading messages in the github action log

- .asf.yaml
This PR updates the `.asf.yaml` file to disable the merge button, update collaborators, and add project labels.
See https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features for an explanation of asf.yaml file and its entries' semantics.
> [hotfix] Update .asf.yaml file to disable the merge button and update collaborators etc.

- flink-ml-core/pom.xml
- flink-ml-iteration/pom.xml
- pom.xml
This PR bumps up the dependency versions for log4j and hadoop libraries to be consistent with apache/flink. And this PR might address the issues in https://github.com/apache/flink-ml/pull/81, https://github.com/apache/flink-ml/pull/84, and https://github.com/apache/flink-ml/pull/85,  which are opened automatically by dependabot.
- Bump hadoop.version from 2.4.1 to 2.8.5
- Bump log4j.version from 2.17.0 to 2.17.1
- If yes, how is the feature documented? (N/A)
> [hotfix] Bump dependency versions

- flink-ml-lib/src/main/java/org/apache/flink/ml/classification/linearsvc/LinearSVC.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/classification/linearsvc/LinearSVCModel.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/classification/linearsvc/LinearSVCModelData.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/classification/linearsvc/LinearSVCModelParams.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/classification/linearsvc/LinearSVCParams.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/common/lossfunc/HingeLoss.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/classification/LinearSVCTest.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/common/lossfunc/HingeLossTest.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/regression/LinearRegressionTest.java
- Add Transformer and Estimator for LinearSVC in FlinkML. 
- Added Transformer and Estimator for LinearSVC.
- Added unit test for Transformer and Estimator for LinearSVC.
> [FLINK-27091] Add Transformer and Estimator for LinearSVC

- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/bucketizer/Bucketizer.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/feature/BucketizerTest.java
- Fix finding buckets error in Bucketizer
- Changed `inputCols` to `splits` in `Bucketizer` and updated the corresponding unit test.
> [hotfix] Fix finding buckets error in Bucketizer

- flink-ml-core/src/main/java/org/apache/flink/ml/param/ParamValidators.java
- flink-ml-core/src/test/java/org/apache/flink/ml/api/StageTest.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/evaluation/binaryclassfication/BinaryClassificationEvaluator.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/evaluation/binaryclassfication/BinaryClassificationEvaluatorParams.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/evaluation/BinaryClassificationEvaluatorTest.java
- Add Transformer for BinaryClassificationEvaluator. 
- Added BinaryClassificationEvaluator.
- Added unit tests for BinaryClassificationEvaluator.
- Added ParamValidators::isSubset.
> [FLINK-27294] Add Transformer for BinaryClassificationEvaluator

- flink-ml-benchmark/README.md
- flink-ml-benchmark/src/main/java/org/apache/flink/ml/benchmark/datagenerator/InputDataGenerator.java
- flink-ml-benchmark/src/main/java/org/apache/flink/ml/benchmark/datagenerator/common/DenseVectorArrayGenerator.java
- flink-ml-benchmark/src/main/java/org/apache/flink/ml/benchmark/datagenerator/common/DenseVectorGenerator.java
- flink-ml-benchmark/src/main/java/org/apache/flink/ml/benchmark/datagenerator/common/LabeledPointWithWeightGenerator.java
- flink-ml-benchmark/src/main/resources/benchmark-demo.json
- flink-ml-benchmark/src/main/resources/kmeans-benchmark.json
- flink-ml-benchmark/src/main/resources/naivebayes-benchmark.json
- flink-ml-benchmark/src/test/java/org/apache/flink/ml/benchmark/BenchmarkTest.java
- flink-ml-benchmark/src/test/java/org/apache/flink/ml/benchmark/DataGeneratorTest.java
- flink-ml-core/src/main/java/org/apache/flink/ml/param/StringArrayArrayParam.java
- flink-ml-core/src/main/java/org/apache/flink/ml/util/ReadWriteUtils.java
- flink-ml-core/src/test/java/org/apache/flink/ml/api/StageTest.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/minmaxscaler/MinMaxScalerParams.java
- pom.xml
This PR adds a `LabeledPointWithWeightGenerator` to `flink-ml-benchmark` module.
`LabeledPointWithWeightGenerator` is used to generate vector-typed features with double-typed label and weight. The generated tables can be used as the train or predict input data of some supervised algorithms. For example,
- Naive Bayes
- Logistic Regression
- Linear Regression
- Linear SVC
- Knn
> [FLINK-27096] Add LabeledPointWithWeightGenerator and Benchmark Configuration for KMeans and NaiveBayes

- flink-ml-iteration/src/main/java/org/apache/flink/iteration/operator/HeadOperatorCheckpointAligner.java
This PR fixes the issue that when there are duplicate checkpoint abort message, the current checkState would directly throws exceptions, which is not expected.
> [FLINK-26801] Support duplicate checkpoint aborted messages

- flink-ml-benchmark/src/main/java/org/apache/flink/ml/benchmark/Benchmark.java
- flink-ml-benchmark/src/main/java/org/apache/flink/ml/benchmark/datagenerator/common/DenseVectorArrayGenerator.java
- flink-ml-benchmark/src/main/java/org/apache/flink/ml/benchmark/datagenerator/common/DenseVectorGenerator.java
- flink-ml-benchmark/src/main/java/org/apache/flink/ml/benchmark/datagenerator/common/DoubleGenerator.java
- flink-ml-benchmark/src/main/java/org/apache/flink/ml/benchmark/datagenerator/common/InputTableGenerator.java
- flink-ml-benchmark/src/main/java/org/apache/flink/ml/benchmark/datagenerator/common/LabeledPointWithWeightGenerator.java
- flink-ml-benchmark/src/main/java/org/apache/flink/ml/benchmark/datagenerator/common/RandomStringGenerator.java
- flink-ml-benchmark/src/main/java/org/apache/flink/ml/benchmark/datagenerator/common/RowGenerator.java
- flink-ml-benchmark/src/main/resources/bucketizer-benchmark.json
- flink-ml-benchmark/src/main/resources/standardscaler-benchmark.json
- flink-ml-benchmark/src/main/resources/stringindexer-benchmark.json
- flink-ml-benchmark/src/test/java/org/apache/flink/ml/benchmark/DataGeneratorTest.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/stringindexer/StringIndexer.java
This PR optimizes the implementation of StringIndexer and introduces several optimizations to the flink-ml-bench.
- Optimizes the implementation of StringIndexer.
- Reduce the length of the operator chain used in generating input tables in flink-ml-bench.
- Added DoubleGenerator and RandomStringGenerator.
- Added configuration for benchmarking StringIndexer, Bucketizer, Standardscaler.
- Enable object reuse in flink-ml-bench.
- If yes, how is the feature documented? (N/A)
> [FLINK-27877] Improve StringIndexer performance and optimize flink-ml-bench

- flink-ml-core/src/main/java/org/apache/flink/ml/common/distance/DistanceMeasure.java
- flink-ml-core/src/main/java/org/apache/flink/ml/common/distance/EuclideanDistanceMeasure.java
- flink-ml-core/src/main/java/org/apache/flink/ml/linalg/BLAS.java
- flink-ml-core/src/main/java/org/apache/flink/ml/linalg/VectorWithNorm.java
- flink-ml-core/src/main/java/org/apache/flink/ml/linalg/typeinfo/DenseVectorSerializer.java
- flink-ml-core/src/main/java/org/apache/flink/ml/linalg/typeinfo/VectorWithNormSerializer.java
- flink-ml-core/src/main/java/org/apache/flink/ml/linalg/typeinfo/VectorWithNormTypeInfo.java
- flink-ml-core/src/main/java/org/apache/flink/ml/linalg/typeinfo/VectorWithNormTypeInfoFactory.java
- flink-ml-core/src/test/java/org/apache/flink/ml/linalg/BLASTest.java
- flink-ml-core/src/test/java/org/apache/flink/ml/linalg/VectorWithNormTest.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/clustering/kmeans/KMeans.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/clustering/kmeans/KMeansModel.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/clustering/kmeans/OnlineKMeans.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/clustering/kmeans/OnlineKMeansModel.java
This PR optimizes KMeans Algorithm's performance with the following modifications.
1. reduce data transmission and per-round operator creation overhead
2. pre-compute the L2 norm of each dense vector and use this information to accelerate the process of finding the closest centroid id of each data point.
After adding the 1st optimization, the throughput of KMeans algorithm increased by around 10%. After introducing the 2nd optimization, the throughput increased by another 60%.
> [FLINK-27096] Optimize KMeans performance

- flink-ml-benchmark/src/main/java/org/apache/flink/ml/benchmark/datagenerator/common/DoubleGenerator.java
- flink-ml-benchmark/src/main/resources/onehotencoder-benchmark.json
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/onehotencoder/OneHotEncoder.java
This PR optimizes the performance of one-hot encoder algorithm with the following modifications:
- Restructures the DAG of OneHotEncoder, so that the very first stream operator can pre-process input data with aggregation operations, so that the data transmission overhead is reduced.
- Avoids unnecessary `String.format()` operation when passing error message to `Precondition.checkArgument`.
These optimizations together reduces the net runtime of OneHotEncoder benchmark jobs to about 1/6.
This PR also does the following:
- Adds example benchmark json file for OneHotEncoder
- Supports generating distinct double values in `DoubleGenerator`.
- This modification has only slight influence on the performance of DoubleGenerator.
> [FLINK-27096] Optimize OneHotEncoder performance

- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/vectorassembler/VectorAssembler.java
This PR optimizes the performance of VectorAssembler. It increases the throughput by 30%-50%.
> [FLINK-27096] Optimize VectorAssembler performance

- docs/config.toml
- flink-ml-examples/pom.xml
This PR is a complement to #117 . It updates the version of flink-ml-examples and docs to 2.2-SNAPSHOT.
> [hotfix] Update examples module and doc's version to 2.2-SNAPSHOT

- flink-ml-examples/src/main/java/org/apache/flink/ml/examples/feature/TokenizerExample.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/bucketizer/Bucketizer.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/tokenizer/Tokenizer.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/tokenizer/TokenizerParams.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/vectorassembler/VectorAssembler.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/feature/TokenizerTest.java
- flink-ml-python/pyflink/examples/ml/feature/tokenizer_example.py
- flink-ml-python/pyflink/ml/lib/feature/bucketizer.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_tokenizer.py
- flink-ml-python/pyflink/ml/lib/feature/tokenizer.py
- Add Transformer for Tokenizer in Flink ML. The parameters of Tokenizer are consistent with that in Spark ML.
- Add Transformer for Tokenizer in Flink ML (Java & Python).
- Add unit test for Tokenizer (Java & Python)
- Add example code for Tokenizer (Java&Python)
> [FLINK-28500] Add Transformer for Tokenizer

- flink-ml-core/src/main/java/org/apache/flink/ml/param/WithParams.java
- flink-ml-examples/src/main/java/org/apache/flink/ml/examples/feature/VectorSlicerExample.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/vectorassembler/VectorAssemblerParams.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/vectorslicer/VectorSlicer.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/vectorslicer/VectorSlicerParams.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/feature/VectorSlicerTest.java
- flink-ml-python/pyflink/examples/ml/feature/vectorslicer_example.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_vectorslicer.py
- flink-ml-python/pyflink/ml/lib/feature/vectorslicer.py
Add Transformer for VectorSlicer in Flink ML.
Add Transformer for VectorSlicer in Flink ML (Java & Python).
Add unit test for VectorSlicer (Java & Python)
Add example code for VectorSlicer (Java&Python)
> [FLINK-28563] Add Transformer for VectorSlicer

- flink-ml-core/src/main/java/org/apache/flink/ml/param/VectorParam.java
- flink-ml-core/src/test/java/org/apache/flink/ml/api/StageTest.java
- flink-ml-examples/src/main/java/org/apache/flink/ml/examples/feature/ElementwiseProductExample.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/elementwiseproduct/ElementwiseProduct.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/elementwiseproduct/ElementwiseProductParams.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/feature/ElementwiseProductTest.java
- flink-ml-python/pyflink/examples/ml/feature/elementwiseproduct_example.py
- flink-ml-python/pyflink/ml/core/param.py
- flink-ml-python/pyflink/ml/core/tests/test_stage.py
- flink-ml-python/pyflink/ml/core/wrapper.py
- flink-ml-python/pyflink/ml/lib/feature/elementwiseproduct.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_elementwiseproduct.py
Add Transformer for ElementwiseProduct
Add Transformer for ElementwiseProduct in Flink ML (Java & Python).
Add unit test for ElementwiseProduct (Java & Python)
Add example code for ElementwiseProduct (Java&Python)
> [FLINK-28611] Add Transformer for ElementwiseProduct

- flink-ml-examples/src/main/java/org/apache/flink/ml/examples/feature/InteractionExample.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/interaction/Interaction.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/interaction/InteractionParams.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/feature/InteractionTest.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/util/TestUtils.java
- flink-ml-python/pyflink/examples/ml/feature/interaction_example.py
- flink-ml-python/pyflink/ml/lib/feature/interaction.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_interaction.py
Add Transformer for Interaction
* Add Transformer for Interaction in Flink ML (Java & Python).
* Add unit test for Interaction (Java & Python)
* Add example code for Interaction (Java&Python)
* Comparing with interaction in spark-ml, we made the following changes:
If the input has nominal features, these features should be one-hot encoded before inputting to this algorithm.
> [FLINK-28894] Add Transformer for Interaction

- flink-ml-examples/src/main/java/org/apache/flink/ml/examples/feature/KBinsDiscretizerExample.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/kbinsdiscretizer/KBinsDiscretizer.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/kbinsdiscretizer/KBinsDiscretizerModel.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/kbinsdiscretizer/KBinsDiscretizerModelData.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/kbinsdiscretizer/KBinsDiscretizerModelParams.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/kbinsdiscretizer/KBinsDiscretizerParams.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/minmaxscaler/MinMaxScaler.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/feature/KBinsDiscretizerTest.java
- flink-ml-python/pyflink/examples/ml/feature/kbinsdiscreteizer_example.py
- flink-ml-python/pyflink/ml/lib/feature/kbinsdiscretizer.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_kbinsdiscretizer.py
- Add Transformer and Estimator for KBinsDiscretizer[1] in Flink ML. 
- Added Transformer and Estimator for KBinsDiscretizer.
- Added java test/example  for Transformer and Estimator for KBinsDiscretizer.
- Added python source/test/example for KBinsDiscretizer.
- Comparing with Sklearn [1], we made the following changes:
- We remove `encode` parameter since we can achieve the same goal with a onehot-encoder following KBinsDiscretizer.
- We remove `random_state` since it is non-trivial to support reproduciable sampling in a distributed setting, while in sklearn (single-node setting), it is much easier. If the users ask for this feature, we can add it later.
- We remove `dtype` since we can achieve the same goal with a simple type conversion following KBinsDiscretizer.
- We support …
> [FLINK-28803] Add Transformer and Estimator for KBinsDiscretizer

- .github/workflows/java8-build.yml
- .github/workflows/python-checks.yml
- flink-ml-core/src/main/java/org/apache/flink/ml/util/ReadWriteUtils.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/classification/KnnTest.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/classification/LinearSVCTest.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/classification/LogisticRegressionTest.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/classification/NaiveBayesTest.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/classification/OnlineLogisticRegressionTest.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/clustering/KMeansTest.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/clustering/OnlineKMeansTest.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/evaluation/BinaryClassificationEvaluatorTest.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/feature/MinMaxScalerTest.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/feature/OneHotEncoderTest.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/regression/LinearRegressionTest.java
- pom.xml
- tools/ci/controller_utils.sh
- tools/ci/java_test_controller.sh
- tools/ci/stage.sh
This PR reduces the total execution time of Flink ML CIs so as to improve the efficiency of Flink ML development.
This PR mainly focuses on optimizing the execution time of Java tests. Python tests might be further optimized in separate PRs.
Compared with the current CI on the master branch, which took about 15 minutes[1], the CI of this PR would complete the same Java tests in about three minutes[2].
[1] https://github.com/apache/flink-ml/actions/runs/2872725840
[2] https://github.com/apache/flink-ml/actions/runs/2879967153
- Make sure all flink-ml-lib tests create a static mini-cluster for all test cases in its class, reducing the overhead to start and shut down clusters
- Disable unaligned checkpoints in test cases
- Split maven tests into multiple CI jobs to improve concurrency.
- …
> [FLINK-27535] Optimize the unit test execution time

- flink-ml-examples/src/main/java/org/apache/flink/ml/examples/feature/MaxAbsScalerExample.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/maxabsscaler/MaxAbsScaler.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/maxabsscaler/MaxAbsScalerModel.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/maxabsscaler/MaxAbsScalerModelData.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/maxabsscaler/MaxAbsScalerParams.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/feature/MaxAbsScalerTest.java
- flink-ml-python/pyflink/examples/ml/feature/maxabsscaler_example.py
- flink-ml-python/pyflink/ml/lib/feature/maxabsscaler.py
- flink-ml-python/pyflink/ml/lib/feature/minmaxscaler.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_maxabsscaler.py
Add Transformer and Estimator of MaxAbsScaler in FlinkML. 
* Add MaxAbsScaler (Java & Python)
* Add MaxAbsScalerModel (Java & Python)
* Add unit test for MaxAbsScaler and MaxAbsScalerModel (Java & Python)
* Add example code for MaxAbsScaler and MaxAbsScalerModel (Java&Python)
Does this pull request introduce a new feature? (no)
> [FLINK-28943] Add Transformer and Estimator for MaxAbsScaler

- flink-ml-iteration/src/main/java/org/apache/flink/iteration/operator/HeadOperator.java
Improve the performance of Flink ML iteration mechanism by reducing the overhead on HeadOperator.
While #144 has reduced the overhead brought by `HeadOperator.endInput()`, it is discovered that the implementation has only reduced the overhead of `Mail`s related to feedback edge. The other mails, like operator events, still need to wait until timeout before they are able to be processed, which is equivalent to `Thread.sleep(timeout)`. Thus we need to improve the implementation in #144 to reduce the overhead for all mails the `HeadOperator` would receive.
The performance improvement brought by this PR on the unit tests of algorithms with iterations is as follows.
|                        | Before this PR [1] | After this PR [2] |
| ---------------------- | ------------------ | …
> [FLINK-29043] Reduce overhead for non-feedback HeadOperator mails

- flink-ml-examples/src/main/java/org/apache/flink/ml/examples/feature/HashingTFExample.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/hashingtf/HashingTF.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/hashingtf/HashingTFParams.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/feature/HashingTFTest.java
- flink-ml-python/pyflink/examples/ml/feature/hashingtf_example.py
- flink-ml-python/pyflink/ml/lib/feature/hashingtf.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_hashingtf.py
- Add Transformer for HashingTF[1] in Flink ML. 
- Added Transformer for HashingTF.
- Added java test/example  for Transformer for HashingTF.
- Added python source/test/example for HashingTF.
- The public interface is consistent with HashingTF in Spark ML [1].
[1] https://spark.apache.org/docs/latest/api/python/reference/api/pyspark.ml.feature.HashingTF.html
> [FLINK-28805] Add Transformer for HashingTF

- flink-ml-examples/src/main/java/org/apache/flink/ml/examples/feature/DCTExample.java
- flink-ml-lib/pom.xml
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/dct/DCT.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/dct/DCTParams.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/feature/DCTTest.java
- flink-ml-python/pyflink/examples/ml/feature/dct_example.py
- flink-ml-python/pyflink/ml/lib/feature/dct.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_dct.py
- flink-ml-uber/src/main/resources/META-INF/NOTICE
- flink-ml-uber/src/main/resources/META-INF/licenses/LICENSE.JLargeArrays
- flink-ml-uber/src/main/resources/META-INF/licenses/LICENSE.JTransforms
Add Transformer for DCT in Flink ML.
- Added Transformer for DCT.
- Added java test/example for DCT.
- Added python source/test/example for DCT.
- The public interface is consistent with DCT in Spark ML.
> [FLINK-29044] Add Transformer for DCT

- flink-ml-examples/src/main/java/org/apache/flink/ml/examples/feature/BinarizerExample.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/binarizer/Binarizer.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/binarizer/BinarizerParams.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/feature/BinarizerTest.java
- flink-ml-python/pyflink/examples/ml/feature/binarizer_example.py
- flink-ml-python/pyflink/ml/lib/feature/binarizer.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_binarizer.py
Add Transformer of Binarizer in FlinkML. 
* Add Binarizer (Java & Python)
* Add unit test for Binarizer (Java & Python)
* Add example code for Binarizer (Java&Python)
The public API, i.e., is any changed class annotated with @public(Evolving): (yes)
> [FLINK-29011] Add Transformer for Binarizer

- docs/content/docs/operators/classification/knn.md
- docs/content/docs/operators/classification/linearsvc.md
- docs/content/docs/operators/classification/logisticregression.md
- docs/content/docs/operators/classification/naivebayes.md
- docs/content/docs/operators/clustering/agglomerativeclustering.md
- docs/content/docs/operators/clustering/kmeans.md
- docs/content/docs/operators/evaluation/binaryclassificationevaluator.md
- docs/content/docs/operators/feature/binarizer.md
- docs/content/docs/operators/feature/bucketizer.md
- docs/content/docs/operators/feature/elementwiseproduct.md
- docs/content/docs/operators/feature/featurehasher.md
- docs/content/docs/operators/feature/hashingtf.md
- docs/content/docs/operators/feature/interaction.md
- docs/content/docs/operators/feature/maxabsscaler.md
- docs/content/docs/operators/feature/onehotencoder.md
- docs/content/docs/operators/feature/standardscaler.md
- docs/content/docs/operators/feature/stringindexer.md
- docs/content/docs/operators/feature/vectorassembler.md
- docs/content/docs/operators/feature/vectorslicer.md
- docs/content/docs/operators/regression/linearregression.md
Add docs of MaxAbs, FeatureHasher, Interaction, VectorSlicer, ElementwiseProduct and Binarizer in Flink ML.
Add docs of MaxAbs, FeatureHasher, Interaction, VectorSlicer, ElementwiseProduct and Binarizer in Flink ML.
Does this pull request introduce a new feature? (no)
If yes, how is the feature documented? (no)
> [FLINK-29171] Add documents for MaxAbs, FeatureHasher, Interaction, VectorSlicer, ElementwiseProduct and Binarizer

- docs/content/docs/operators/feature/normalizer.md
- flink-ml-core/src/main/java/org/apache/flink/ml/linalg/BLAS.java
- flink-ml-core/src/test/java/org/apache/flink/ml/linalg/BLASTest.java
- flink-ml-examples/src/main/java/org/apache/flink/ml/examples/feature/NormalizerExample.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/normalizer/Normalizer.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/normalizer/NormalizerParams.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/feature/NormalizerTest.java
- flink-ml-python/pyflink/examples/ml/feature/normalizer_example.py
- flink-ml-python/pyflink/ml/lib/feature/normalizer.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_normalizer.py
Add Transformer for Normalizer in Flink ML.
Added java/python source/test/example for Transformer for Normalizer in Flink ML.
The public interface is consistent with Normalizer in Spark ML.
Dependencies (does it add or upgrade a dependency): (yes)
> [FLINK-29193] Add Transformer for Normalizer

- docs/content/docs/operators/feature/ngram.md
- flink-ml-examples/src/main/java/org/apache/flink/ml/examples/feature/NGramExample.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/ngram/NGram.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/ngram/NGramParams.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/feature/NGramTest.java
- flink-ml-python/pyflink/examples/ml/feature/ngram_example.py
- flink-ml-python/pyflink/ml/lib/feature/ngram.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_ngram.py
Add Transformer for NGram in Flink ML.
- Added java/python source/test/example and user doc for Transformer for NGram in Flink ML.
- The public interface is consistent with NGram in Spark ML.
> [FLINK-29168] Add Transformer for NGram

- docs/content/docs/operators/feature/idf.md
- flink-ml-core/src/main/java/org/apache/flink/ml/common/datastream/DataStreamUtils.java
- flink-ml-core/src/main/java/org/apache/flink/ml/common/datastream/TableUtils.java
- flink-ml-core/src/test/java/org/apache/flink/ml/common/datastream/DataStreamUtilsTest.java
- flink-ml-examples/src/main/java/org/apache/flink/ml/examples/feature/IDFExample.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/idf/IDF.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/idf/IDFModel.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/idf/IDFModelData.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/idf/IDFModelParams.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/idf/IDFParams.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/feature/IDFTest.java
- flink-ml-python/pyflink/examples/ml/feature/idf_example.py
- flink-ml-python/pyflink/ml/lib/feature/idf.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_idf.py
Add Transformer and Estimator for IDF in Flink ML.
- Added java/python source/test/example for Transformer and Estimator for IDF in Flink ML.
- The public interface is consistent with IDF in Spark ML.
> [FLINK-28806] Add Transformer and Estimator for IDF

- docs/content/docs/operators/clustering/agglomerativeclustering.md
- flink-ml-core/src/main/java/org/apache/flink/ml/common/datastream/DataStreamUtils.java
- flink-ml-core/src/main/java/org/apache/flink/ml/common/window/CountTumblingWindows.java
- flink-ml-core/src/main/java/org/apache/flink/ml/common/window/EventTimeSessionWindows.java
- flink-ml-core/src/main/java/org/apache/flink/ml/common/window/EventTimeTumblingWindows.java
- flink-ml-core/src/main/java/org/apache/flink/ml/common/window/GlobalWindows.java
- flink-ml-core/src/main/java/org/apache/flink/ml/common/window/ProcessingTimeSessionWindows.java
- flink-ml-core/src/main/java/org/apache/flink/ml/common/window/ProcessingTimeTumblingWindows.java
- flink-ml-core/src/main/java/org/apache/flink/ml/common/window/Windows.java
- flink-ml-core/src/main/java/org/apache/flink/ml/param/WindowsParam.java
- flink-ml-core/src/test/java/org/apache/flink/ml/api/StageTest.java
- flink-ml-core/src/test/java/org/apache/flink/ml/common/window/WindowsTest.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/clustering/agglomerativeclustering/AgglomerativeClustering.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/clustering/agglomerativeclustering/AgglomerativeClusteringParams.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/common/param/HasWindows.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/clustering/AgglomerativeClusteringTest.java
- flink-ml-python/pyflink/ml/core/param.py
- flink-ml-python/pyflink/ml/core/tests/test_param.py
- flink-ml-python/pyflink/ml/core/tests/test_stage.py
- flink-ml-python/pyflink/ml/core/windows.py
- flink-ml-python/pyflink/ml/core/wrapper.py
- flink-ml-python/pyflink/ml/lib/clustering/agglomerativeclustering.py
- flink-ml-python/pyflink/ml/lib/clustering/tests/test_agglomerativeclustering.py
- flink-ml-python/pyflink/ml/lib/param.py
This PR introduces the `Windows` interface and several implementations of this interface that can be used to slice input streams into finite batches and fed them into Flink ML stages. On the basis of these changes, this PR adds a `windows` parameter to AgglomerativeClustering so that it can work on unbounded input streams.
- Add `Windows` interface and its subclasses, `Count/EventTime/ProcessingTime + Tumbling/Session + Windows`.
- Add `windows` parameter on AgglomerativeClustering and make it able to deal with the infinite input stream.
> [FLINK-28906] Support windowing in AgglomerativeClustering

- docs/content/docs/operators/feature/polynomialexpansion.md
- flink-ml-examples/src/main/java/org/apache/flink/ml/examples/feature/PolynomialExpansionExample.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/polynomialexpansion/PolynomialExpansion.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/polynomialexpansion/PolynomialExpansionParams.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/feature/PolynomialExpansionTest.java
- flink-ml-python/pyflink/examples/ml/feature/polynomialexpansion_example.py
- flink-ml-python/pyflink/ml/lib/feature/polynomialexpansion.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_polynomialexpansion.py
Add Transformer for PolynomialExpansion in Flink ML.
Added java/python source/test/example for Transformer for PolynomialExpansion in Flink ML.
The public interface is consistent with PolynomialExpansion in Spark ML.
> [FLINK-29318] Add Transformer for PolynomialExpansion

- docs/content/docs/operators/feature/variancethresholdselector.md
- flink-ml-examples/src/main/java/org/apache/flink/ml/examples/feature/VarianceThresholdSelectorExample.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/variancethresholdselector/VarianceThresholdSelector.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/variancethresholdselector/VarianceThresholdSelectorModel.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/variancethresholdselector/VarianceThresholdSelectorModelData.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/variancethresholdselector/VarianceThresholdSelectorModelParams.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/variancethresholdselector/VarianceThresholdSelectorParams.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/feature/VarianceThresholdSelectorTest.java
- flink-ml-python/pyflink/examples/ml/feature/variancethresholdselector_example.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_variancethresholdselector.py
- flink-ml-python/pyflink/ml/lib/feature/variancethresholdselector.py
- flink-ml-python/pyflink/ml/tests/test_utils.py
Adding Transformer and Estimator for VarianceThresholdSelector
- Added java/python source/test/example for Transformer and Estimator for VarianceThresholdSelector in Flink ML.
> [FLINK-29409] Add Transformer and Estimator for VarianceThresholdSelector

- docs/content/docs/operators/stats/_index.md
- docs/content/docs/operators/stats/chisqtest.md
- flink-ml-examples/src/main/java/org/apache/flink/ml/examples/stats/ChiSqTestExample.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/stats/chisqtest/ChiSqTest.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/stats/chisqtest/ChiSqTestParams.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/stats/ChiSqTestTest.java
- flink-ml-python/pyflink/examples/ml/stats/__init__.py
- flink-ml-python/pyflink/examples/ml/stats/chisqtest_example.py
- flink-ml-python/pyflink/ml/lib/stats/__init__.py
- flink-ml-python/pyflink/ml/lib/stats/chisqtest.py
- flink-ml-python/pyflink/ml/lib/stats/common.py
- flink-ml-python/pyflink/ml/lib/stats/tests/__init__.py
- flink-ml-python/pyflink/ml/lib/stats/tests/test_chisqtest.py
- flink-ml-python/pyflink/ml/lib/tests/test_ml_lib_completeness.py
- flink-ml-python/setup.py
This PR aligns the behavior of ChiSqTest with that of Spark, and adds corresponding Python API and documents.
- Change the input features of ChiSqTest from multiple arbitrary columns to one vector column, and the input label of ChiSqTest from arbitrary java object to numbers. As a result, the input and output types of all operators in ChiSqTest are changed from string or arbitrary types to number or vector types.
- Add support for the flatten parameter in ChiSqTest
- Add module `stats` to Flink ML Python API
- Add ChiSqTest's Python implementation
- Add ChiSqTest's Java/Python example
- Add ChiSqTest's website document
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes)
- Does this pull request …
> [FLINK-28571] Improve API and Document of ChiSqTest

- docs/content/docs/operators/functions.md
- flink-ml-examples/src/main/java/org/apache/flink/ml/examples/ArrayToVectorExample.java
- flink-ml-examples/src/main/java/org/apache/flink/ml/examples/VectorToArrayExample.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/Functions.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/FunctionsTest.java
- flink-ml-python/pyflink/examples/ml/arraytovector_example.py
- flink-ml-python/pyflink/examples/ml/vectortoarray_example.py
- flink-ml-python/pyflink/ml/core/wrapper.py
- flink-ml-python/pyflink/ml/lib/functions.py
- flink-ml-python/pyflink/ml/lib/tests/test_functions.py
This PR adds functions to convert between Vectors and numerical arrays
- Adds ScalarFunctions to convert Vectors to arrays and back.
- Adds static utility functions to wrap the conversion logic.
- Improves support for DenseVector type information in python.
- Adds examples and documentation of the utility functions above.
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes)
> [FLINK-29591] Add built-in UDFs to convert between arrays and vectors

- flink-ml-core/src/main/java/org/apache/flink/ml/common/broadcast/BroadcastUtils.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/common/util/QuantileSummary.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/common/util/QuantileSummaryTest.java
Add QuantileSummary to help calculate approximate quantiles
- Add implementation of GK algorithm.
- Add merge operation to combine results of distributed datasets.
- Remove redundant Internal annotations from BroadcastUtils
- Does this pull request introduce a new feature? (yes )
> [FLINK-29593] Add QuantileSummary to help calculate approximate quantiles

- flink-ml-lib/src/main/java/org/apache/flink/ml/clustering/agglomerativeclustering/AgglomerativeClustering.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/clustering/AgglomerativeClusteringTest.java
Fix the bug in AgglomerativeClustering that we did not stop the clustering process when the size of the active clusters is already one.
- Stops the clustering process when size of the active clusters is one
- Add unit test to cover the bug.
> [FLINK-29824] Stop clustering when size of the active clusters is one

- flink-ml-core/src/main/java/org/apache/flink/ml/common/distance/EuclideanDistanceMeasure.java
- flink-ml-core/src/test/java/org/apache/flink/ml/common/distance/DistanceMeasureTest.java
This PR fixes the bug that `EuclideanDistanceMeasure.distanceSquare(...)` method might return negative values due to loss of data accuracy.
- Fixes the bug by setting distance square as `Math.max(0, norm1 * norm1 + norm2 * norm2 - 2 * vec1 \dot vec2) `
- Adds corresponding test cases.
> [FLINK-29843] Avoid negative euclidean distance square

- docs/content/docs/operators/feature/vectorassembler.md
- flink-ml-examples/src/main/java/org/apache/flink/ml/examples/feature/VectorAssemblerExample.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/vectorassembler/VectorAssembler.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/vectorassembler/VectorAssemblerParams.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/feature/VectorAssemblerTest.java
- flink-ml-python/pyflink/examples/ml/feature/vectorassembler_example.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_vectorassembler.py
- flink-ml-python/pyflink/ml/lib/feature/vectorassembler.py
Add inputSizes parameter for VectorAssembler
Add inputSizes parameter for VectorAssembler.
The public API, i.e., is any changed class annotated with @public(Evolving): (yes)
> [FLINK-29323] Add inputSizes parameter for VectorAssembler

- flink-ml-core/src/main/java/org/apache/flink/ml/common/datastream/DataStreamUtils.java
- flink-ml-core/src/test/java/org/apache/flink/ml/common/datastream/DataStreamUtilsTest.java
This PR fixes the NPE that would possibly be thrown when using `DataStreamUtils.aggregate`.
- Save only non-null values in the aggregate utility function's state.
- Clarify the behavior of the aggregate utility function in respect of input parallelism and add a test for the corner case.
> [FLINK-30014][hotfix] Ensure saving non-null value in aggregate util function state

- docs/content/docs/operators/feature/sqltransformer.md
- flink-ml-examples/src/main/java/org/apache/flink/ml/examples/feature/SQLTransformerExample.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/sqltransformer/SQLTransformer.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/sqltransformer/SQLTransformerParams.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/feature/SQLTransformerTest.java
- flink-ml-python/pyflink/examples/ml/feature/sqltransformer_example.py
- flink-ml-python/pyflink/ml/lib/feature/sqltransformer.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_sqltransformer.py
This PR adds the Transformer for the SQL transformer algorithm.
- Adds Transformer implementation of SQL transformer in Java and Python
- Adds examples and documentation of SQL transformer
> [FLINK-29602] Add Transformer for SQLTransformer

- flink-ml-python/pyflink/ml/lib/classification/tests/test_knn.py
- flink-ml-python/pyflink/ml/lib/classification/tests/test_linearsvc.py
- flink-ml-python/pyflink/ml/lib/classification/tests/test_naivebayes.py
- flink-ml-python/pyflink/ml/lib/clustering/tests/test_kmeans.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_idf.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_imputer.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_indextostringmodel.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_kbinsdiscretizer.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_maxabsscaler.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_minmaxscaler.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_onehotencoder.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_robustscaler.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_standardscaler.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_stringindexer.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_variancethresholdselector.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_vectorindexer.py
- flink-ml-python/pyflink/ml/tests/test_utils.py
This PR adds python tests for the public APIs of Flink ML algorithms.
Adds test cases for the following APIs for all existing offline algorithms in Flink ML. The tests added in this PR are as follows.
| Name of Algorithm         | setModelData() | getModelData()  | Save/load |
| ------------------------- | -------------- | --------------- | --------- |
| KNN                       | O              | O               | --        |
| LinearSVC                 | O              | O               | O         |
| LogisticRegression        | --             | --              | --        |
| NaiveBayes                | O              | X (FLINK-30124) | --        |
| AgglomerativeClustering   | -              | -               | --        |
| KMeans                    | O              | X …
> [FLINK-30099] Add test case for algorithms' python APIs

- flink-ml-python/pyflink/ml/tests/test_utils.py
All python tests are currently run with execution.attached=false by default. Thus `env.execute()` can return the `JobExecutionResult` before the execution finishes. 
This breaks that tests such as `RobustScalerTest::test_save_load_predict()`, as the test will attempt to load model data from files before the data has been fully written to the files by the previous Flink job.
This PR fixes the issue described above by setting execution.attached=true for all python tests so that `env.execute()` will only return after the job finishes.
A followup PR is needed to set execution.attached=true for all Java tests.
Updates `PyFlinkMLTestCase` to configure StreamExecutionEnvironment with execution.attached=True.
- The public API, i.e., is …
> [hotfix] Update python tests to set execution.attached=True

- .github/workflows/python-checks.yml
- flink-ml-python/pom.xml
- flink-ml-python/pyflink/ml/tests/test_utils.py
- pom.xml
This pull request optimizes the efficiency of Flink ML python tests by enabling the use of shared mini cluster in python tests. The using of shared mini cluster is implemented in reference to https://github.com/apache/flink/pull/20685.
Before optimization: https://github.com/apache/flink-ml/actions/runs/3569792445
| Name of test                  | Duration |
| ----------------------------- | -------- |
| Python tests on macOS-latest  | 27m11s   |
| Python tests on macOS-latest  | 1h13m    |
| Python tests on macOS-latest  | 37m21s   |
| Python tests on ubuntu-latest | 19m9s    |
| Python tests on ubuntu-latest | 27m37s   |
| Python tests on ubuntu-latest | 33m45s   |
After optimization: https://github.com/apache/flink-ml/actions/runs/3571587319
| Name of test                      | …
> [FLINK-30037] Use shared mini-cluster in python tests

- flink-ml-dist/pom.xml
- flink-ml-dist/src/main/assemblies/bin.xml
- flink-ml-lib/src/main/java/org/apache/flink/ml/classification/naivebayes/NaiveBayes.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/imputer/Imputer.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/vectorindexer/VectorIndexer.java
- flink-ml-python/pom.xml
- flink-ml-python/pyflink/ml/core/wrapper.py
- flink-ml-python/pyflink/ml/lib/classification/tests/test_naivebayes.py
- flink-ml-python/pyflink/ml/lib/clustering/tests/test_kmeans.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_idf.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_imputer.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_indextostringmodel.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_kbinsdiscretizer.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_stringindexer.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_variancethresholdselector.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_vectorindexer.py
- flink-ml-python/src/main/java/org/apache/flink/ml/python/PythonBridgeUtils.java
This pull request provides solutions for FLINK-30124 and FLINK-30122 and temporary walkrounds for FLINK-29477 and FLINK-30168。
- Adds `flink-ml-python` module, overriding certain methods in `org.apache.flink.api.common.python.PythonBridgeUtils` to provide proper support for records of object arrays and primitive arrays.
- Modifies the schema of the model data table of `NaiveBayes`, `Imputer,` and `VectorIndexer` from `GenericTypeInfo<java.util.Map>` to `MapTypeInfo`.
- Add Python tests for the getModelData() method of the algorithms affected by these problems.
- If yes, how is the feature …
> [FLINK-30124] Support collecting model data with arrays and maps

- flink-ml-lib/src/main/java/org/apache/flink/ml/clustering/agglomerativeclustering/AgglomerativeClustering.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/clustering/AgglomerativeClusteringTest.java
- flink-ml-python/pyflink/ml/lib/clustering/tests/test_agglomerativeclustering.py
This PR aims to improve the performance of AgglomerativeClustering.
- Improves the performance of AgglomerativeClustering by more than 10x, following "Modern hierarchical, agglomerative clustering algorithms", by Daniel Mullner. For example given 4K input data points, the old implementation needs ~120s, while this PR needs ~10s.
- Fixed on corner case when using linkage as `ward` and distance as `euclidean`.
- Fixed some typos in UT.
> [FLINK-29911] Improve performance of AgglomerativeClustering

- flink-ml-benchmark/src/main/resources/vectorassembler-benchmark.json
- Change the data generator of VectorAssembler from `ColsWithLabelGenerator` to `DoubleGenerator`
- If yes, how is the feature documented? (not documented)
> [FLINK-30523]  Fix the data generator for VectorAssembler benchmark

- docs/content/docs/operators/feature/randomsplitter.md
- flink-ml-examples/src/main/java/org/apache/flink/ml/examples/feature/RandomSplitterExample.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/randomsplitter/RandomSplitter.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/randomsplitter/RandomSplitterParams.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/feature/RandomSplitterTest.java
- flink-ml-python/pyflink/examples/ml/feature/randomsplitter_example.py
- flink-ml-python/pyflink/ml/lib/feature/randomsplitter.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_randomsplitter.py
- Add HasSeed param for RandomSplitter.
- Add API setSeed() for RandomSplitter Transformer in Java and Python. 
- This parameter guarantees reproduciable output only when the paralleism is unchanged and each worker reads the same data in the same order.
- Add ut for this new API.
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes)
- If yes, how is the feature documented? (docs)
> [FLINK-30348] Add HasSeed param for RandomSplitter

- docs/content/docs/operators/feature/minhashlsh.md
- flink-ml-core/src/main/java/org/apache/flink/ml/common/datastream/DataStreamUtils.java
- flink-ml-examples/src/main/java/org/apache/flink/ml/examples/feature/MinHashLSHExample.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/lsh/LSH.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/lsh/LSHModel.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/lsh/LSHModelData.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/lsh/LSHModelParams.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/lsh/LSHParams.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/lsh/MinHashLSH.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/lsh/MinHashLSHModel.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/lsh/MinHashLSHModelData.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/lsh/MinHashLSHParams.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/feature/MinHashLSHTest.java
- flink-ml-python/pyflink/examples/ml/feature/minhashlsh_example.py
- flink-ml-python/pyflink/ml/lib/feature/lsh.py
- flink-ml-python/pyflink/ml/lib/feature/tests/test_minhashlsh.py
- flink-ml-python/pyflink/ml/lib/tests/test_ml_lib_completeness.py
This pull request adds the implementation of MinHash LSH algorithm.
- Adds base Transformer and Estimator of LSH algorithms
- Adds Transformer and Estimator implementation of MinHash LSH in Java and Python
- Adds examples and documentations of MinHash LSH
- Does this pull request introduce a new feature? yes
- If yes, how is the feature documented? docs / JavaDocs
> [FLINK-30401] Add Estimator and Transformer for MinHashLSH

- pom.xml
The original PR which modified the flink-parent: #https://github.com/apache/flink/pull/21606
This PR aims to publish SBOM artifacts.
- Here is an article to give some context: [article](https://www.activestate.com/blog/why-the-us-government-is-mandating-software-bill-of-materials-sbom/)
Software Bill of Materials (SBOM) are additional artifacts containing the aggregate of all direct and transitive dependencies of a project. The US Government (based on NIST recommendations) currently accepts only the three most popular SBOM standards as valid, namely: [CycloneDX](https://cyclonedx.org/), [Software Identification (SWID) tag](https://csrc.nist.gov/projects/Software-Identification-SWID), [Software Package Data Exchange® (SPDX)](https://spdx.dev/).
This PR uses [CycloneDX maven …
> [FLINK-30578][build] Publish SBOM artifacts

- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/stringindexer/StringIndexer.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/stringindexer/StringIndexerModel.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/feature/stringindexer/StringIndexerTest.java
- flink-ml-python/pyflink/ml/feature/tests/test_stringindexer.py
This PR fixes null values handling in StringIndexer and StringIndexerModel.
- Skip null values in training, and handle null values in transforming.
- Add tests for null values handling in corresponding test class.
> [FLINK-30730] Fix null values handling in StringIndexer and StringIndexerModel

- flink-ml-lib/src/test/java/org/apache/flink/ml/feature/stringindexer/StringIndexerTest.java
Fix a failed test in StringIndexerTest, which is encountered with certain probability.
To be specific, in the last assertion of StringIndexerTest#testHandleInvalid, one of multiple values could trigger the exception. All possible values should be considered when building the set of expected messages, yet existing code misses one value. This PR adds the missing value and improves the assertion message.
- Fixes the assertion in the failed test.
> [FLINK-30730][followup] Fix test failure in StringIndexerTest

- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/kbinsdiscretizer/KBinsDiscretizer.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/feature/KBinsDiscretizerTest.java
- flink-ml-python/pyflink/ml/feature/kbinsdiscretizer.py
- flink-ml-python/pyflink/ml/feature/tests/test_kbinsdiscretizer.py
KBinsDiscretizer produces `{Double.MIN_VALUE, Double.MAX_VALUE}` for columns whose input values are same which is not correct, as it doesn't cover negative values and 0. A more reasonable value should be `{Double.NEGATIVE_INFINITY, Double.POSITIVE_INFINITY}`.
- Change bin edges for columns whose input values are same to `{Double.NEGATIVE_INFINITY, Double.POSITIVE_INFINITY}`.
> [FLINK-31026] Fix KBinsDiscretizer when the input values of one column are same

- flink-ml-benchmark/src/main/java/org/apache/flink/ml/benchmark/Benchmark.java
- flink-ml-benchmark/src/test/java/org/apache/flink/ml/benchmark/BenchmarkTest.java
- flink-ml-benchmark/src/test/java/org/apache/flink/ml/benchmark/DataGeneratorTest.java
- flink-ml-core/src/test/java/org/apache/flink/ml/api/StageTest.java
- flink-ml-core/src/test/java/org/apache/flink/ml/common/datastream/TableUtilsTest.java
- flink-ml-core/src/test/java/org/apache/flink/ml/util/TestUtils.java
- flink-ml-iteration/src/main/java/org/apache/flink/iteration/Iterations.java
- flink-ml-iteration/src/main/java/org/apache/flink/iteration/operator/HeadOperator.java
- flink-ml-iteration/src/main/java/org/apache/flink/iteration/operator/headprocessor/HeadOperatorState.java
- flink-ml-iteration/src/main/java/org/apache/flink/iteration/typeinfo/IterationRecordTypeInfo.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/classification/logisticregression/OnlineLogisticRegression.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/classification/LinearSVCTest.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/classification/LogisticRegressionTest.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/clustering/KMeansTest.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/clustering/OnlineKMeansTest.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/feature/HashingTFTest.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/feature/OnlineStandardScalerTest.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/regression/LinearRegressionTest.java
- flink-ml-tests/src/test/java/org/apache/flink/test/iteration/BoundedAllRoundCheckpointITCase.java
- flink-ml-tests/src/test/java/org/apache/flink/test/iteration/BoundedPerRoundCheckpointITCase.java
Disable Kryo fallback for all tests (except `OnlineLogisticRegressionTest`) in flink-ml-lib to ensure that all Flink ML algorithms can run without relying on Kryo for serialization and deserialization.
In addition, this PR also updates `Benchmark#executeBenchmarks` to disable Kryo fallback to make sure that our benchmarks (including data generators) do not reply on Kryo.
Disabled Kryo fallback in the following classes and methods:
- OnlineStandardScalerTest
- LogisticRegressionTest
- KMeansTest
- OnlineKMeansTest
- LinearSVCTest
- LinearRegressionTest
- HashingTFTest
- Benchmark#executeBenchmarks
- TableUtilsTest
- Does this pull request introduce a …
> [FLINK-30688][followup] Disable Kryo fallback for tests in flink-ml-lib

- flink-ml-benchmark/src/main/java/org/apache/flink/ml/benchmark/datagenerator/common/DenseVectorArrayGenerator.java
- flink-ml-benchmark/src/main/java/org/apache/flink/ml/benchmark/datagenerator/common/DenseVectorGenerator.java
- flink-ml-benchmark/src/main/java/org/apache/flink/ml/benchmark/datagenerator/common/DoubleGenerator.java
- flink-ml-benchmark/src/main/java/org/apache/flink/ml/benchmark/datagenerator/common/LabeledPointWithWeightGenerator.java
- flink-ml-benchmark/src/main/java/org/apache/flink/ml/benchmark/datagenerator/common/RandomStringArrayGenerator.java
- flink-ml-benchmark/src/main/java/org/apache/flink/ml/benchmark/datagenerator/common/RandomStringGenerator.java
- flink-ml-benchmark/src/main/java/org/apache/flink/ml/benchmark/datagenerator/common/RowGenerator.java
- flink-ml-core/src/main/java/org/apache/flink/ml/common/datastream/TableUtils.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/bucketizer/Bucketizer.java
Minimize the source operator overhead in Flink ML benchmark and optimize the bucketizer performance.
Here is the total execution time of the Bucketizer benchmark for 3 different setups. The execution time is obtained by taking the average execution time across 5 runs for each setup.
- Execution time is 33.26 sec prior to this PR.
- Execution time is 31.14 sec after optimizing the benchmark framework.
- Execution time is 30.88 sec after optimizing both the benchmark framework and the Bucketizer.
Thus the benchmark framework optimization reduces the total time by 6.4%. The Bucketizer reduces the total time by another 0.83%.
- Updated RowGenerator to pre-generate at least 1/000 of the expected number of rows  and re-use those rows as the source function output.
- Renamed RowGenerator#nextRow …
> [FLINK-31125] Flink ML benchmark framework should minimize the source operator overhead

- flink-ml-core/src/main/java/org/apache/flink/ml/api/Transformer.java
- flink-ml-servable-core/src/main/java/org/apache/flink/ml/linalg/DenseMatrix.java
- flink-ml-servable-core/src/main/java/org/apache/flink/ml/linalg/DenseVector.java
- flink-ml-servable-core/src/main/java/org/apache/flink/ml/linalg/SparseVector.java
- flink-ml-servable-core/src/main/java/org/apache/flink/ml/linalg/Vector.java
- flink-ml-servable-core/src/main/java/org/apache/flink/ml/linalg/Vectors.java
- flink-ml-servable-core/src/main/java/org/apache/flink/ml/servable/api/DataFrame.java
- flink-ml-servable-core/src/main/java/org/apache/flink/ml/servable/api/ModelServable.java
- flink-ml-servable-core/src/main/java/org/apache/flink/ml/servable/api/Row.java
- flink-ml-servable-core/src/main/java/org/apache/flink/ml/servable/api/TransformerServable.java
- flink-ml-servable-core/src/main/java/org/apache/flink/ml/servable/types/BasicType.java
- flink-ml-servable-core/src/main/java/org/apache/flink/ml/servable/types/DataType.java
- flink-ml-servable-core/src/main/java/org/apache/flink/ml/servable/types/MatrixType.java
- flink-ml-servable-core/src/main/java/org/apache/flink/ml/servable/types/ScalarType.java
- flink-ml-servable-core/src/main/java/org/apache/flink/ml/servable/types/VectorType.java
Add public API classes for FLIP-289 with the exception specified below.
Added most public API classes specified in FLIP-289.
The following class and methods are not added:
- GraphModel#supportServable
- PipelineModel#supportServable
- PipelineModelServable
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: yes
- Does this pull request introduce a new feature? yes
- If yes, how is the feature documented? JavaDocs
> [FLINK-31127] Add public API classes for FLIP-289

- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/vectorindexer/VectorIndexer.java
- Fix NPE in VectorIndexer.
- Add check for `doublesByColumn` when doing snapshot.
> [FLINK-31191] Fix null pointer exception in VectorIndexer

- flink-ml-iteration/src/main/java/org/apache/flink/iteration/operator/HeadOperator.java
- flink-ml-iteration/src/main/java/org/apache/flink/iteration/operator/OutputOperator.java
- flink-ml-tests/src/test/java/org/apache/flink/test/iteration/BoundedPerRoundStreamIterationITCase.java
Currently, when executing join for bounded input streams in a perround iteration body, there exist two problems:
- The program may not exit even the result is collected using `datastream.executeAndCollect()`
- The max watermark of the output stream is losed.
This PR attempts to fix the above problems.
- Set `Timer` thread as daemon in `HeadOperator`.
- Outputs maxwatermark when encountering max epoch watermark in `OutputOperator`.
- Added unit test for verify the change.
> [FLINK-30933] Fix missing max watermark when executing join in iteration body

- flink-ml-iteration/src/main/java/org/apache/flink/iteration/operator/OperatorUtils.java
- flink-ml-iteration/src/main/java/org/apache/flink/iteration/operator/allround/AbstractAllRoundWrapperOperator.java
- flink-ml-iteration/src/main/java/org/apache/flink/iteration/operator/perround/AbstractPerRoundWrapperOperator.java
Obtains the KeySelector with UserClassLoader instead of AppClassLoader to fix [FLINK-31486](https://issues.apache.org/jira/browse/FLINK-31486).
- Obtains the KeySelector with UserClassLoader.
> [FLINK-31486] Get the KeySelector with UserClassLoader

- docs/content/docs/operators/feature/countvectorizer.md
- docs/content/docs/operators/feature/elementwiseproduct.md
- docs/content/docs/operators/feature/featurehasher.md
- docs/content/docs/operators/feature/indextostring.md
- docs/content/docs/operators/feature/maxabsscaler.md
- docs/content/docs/operators/feature/minhashlsh.md
- docs/content/docs/operators/feature/minmaxscaler.md
- docs/content/docs/operators/feature/onehotencoder.md
- docs/content/docs/operators/feature/robustscaler.md
- docs/content/docs/operators/feature/standardscaler.md
- docs/content/docs/operators/feature/stringindexer.md
- docs/content/docs/operators/feature/univariatefeatureselector.md
- docs/content/docs/operators/feature/variancethresholdselector.md
- docs/content/docs/operators/feature/vectorassembler.md
- docs/content/docs/operators/feature/vectorslicer.md
Make the feature engineering algorithm names consistent in the website https://nightlies.apache.org/flink/flink-ml-docs-master/docs/operators/feature/binarizer/. This approach is also consistent with Spark ML's website doc https://spark.apache.org/docs/latest/ml-features.
In addition, we should list `IndexToStringModel` as a top-level algorithm instead of describing it as part of `StringIndexer` in the website doc because they can be used separately.
- Updated website doc to avoid space in the feature engineering algorithm names.
- Moved the description of `IndexToStringModel` from stringindexer.md to indextostring.md.
- Does this pull request …
> [hotfix][doc] Update website doc to avoid space in the feature engineering algorithm names

- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/kbinsdiscretizer/KBinsDiscretizer.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/feature/KBinsDiscretizerTest.java
- flink-ml-python/pyflink/ml/feature/kbinsdiscretizer.py
- flink-ml-python/pyflink/ml/feature/tests/test_kbinsdiscretizer.py
This PR aims to fix the bug when using quantile strategy in KbinsDiscretizer. 
- In the original version, we remove bins with zero width by simply merging it with the next bin. However it is not always true. For example, if the histograms computed are [0, 0, 0, 1], then it is transformed into [0, 1]. Thus is 0 and 1 are mapped in to the same bin, which is wrong.
- In this PR, the histogram will be transformed into [0, 0.5, 1]. It is computed with the following logic:
- Remove the repeated elements in the histgram such that there are no 3+ consecutive same elements.
- If there two consecutive same elements, the second one is updated as the average of the element before and after.
- If the last two elements in the histogram are the same, the last one is removed.
- Changed the computing …
> [FLINK-31029] Fix bug when using quantile in KbinsDiscretizer

- docs/content/docs/operators/feature/stringindexer.md
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/stringindexer/StringIndexer.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/stringindexer/StringIndexerModel.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/feature/stringindexer/StringIndexerParams.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/feature/stringindexer/StringIndexerTest.java
- flink-ml-python/pyflink/ml/feature/stringindexer.py
- flink-ml-python/pyflink/ml/feature/tests/test_stringindexer.py
This PR aims to support the use case when users want to filter out infrequent strings in StringIndexer.
To achieve this, I have added a `HasMaxIndexNum` param. The default value is `Int.MAX` so it is consistent with the existing behavior.
Note that `HasMaxIndexNum` only works when `stringOrderType` is set as `frequencyDesc`.
- Added `HasMaxIndexNum` param and the corresponding logic.
- Added java/python test
- Updated the correponding doc.
- If yes, how is the feature documented? (javaDocs)
> [FLINK-31189] Add HasMaxIndexNum param to StringIndexer

- flink-ml-core/src/main/java/org/apache/flink/ml/common/datastream/DataStreamUtils.java
- flink-ml-core/src/test/java/org/apache/flink/ml/common/datastream/DataStreamUtilsTest.java
This modification will resolve the issue with `DataStreamUtils#sample` by implementing uniform sampling.
The current implementation utilizes a two-level sampling method. However, if the elements are unevenly distributed among partitions (subtasks), the sampling probabilities may differ across partitions, resulting in non-uniform sampling.
Furthermore, the current implementation has a side-effect where one subtask has a memory footprint of `2 * numSamples * sizeof(element)`, potentially leading to unexpected OOM errors in certain scenarios.
- Adds `rebalance` to the input data, and decrease the number of samples in the first round.
- Adds unit tests for this method.
- Dependencies (does it add or upgrade a dependency): (yes / no) no
- The public API, i.e., is any changed class annotated …
> [FLINK-31623] Fix DataStreamUtils#sample with approximate uniform sampling

- flink-ml-iteration/src/main/java/org/apache/flink/iteration/proxy/ProxyStreamPartitioner.java
- flink-ml-tests/src/test/java/org/apache/flink/test/iteration/BoundedAllRoundStreamIterationITCase.java
- flink-ml-tests/src/test/java/org/apache/flink/test/iteration/BoundedPerRoundStreamIterationITCase.java
Make the ProxyStreamPartitioner implement ConfigurableStreamPartitioner. Otherwise, the KeyGroupRange that is computed in StreamTaskStateInitializerImpl.java doesn't match the subTaskId that is computed in KeyGroupStreamPartitioner.java.
For more information, please refer to the [blog](https://flink.apache.org/2017/07/04/a-deep-dive-into-rescalable-state-in-apache-flink/).
- Make the ProxyStreamPartitioner implement ConfigurableStreamPartitioner.
> [FLINK-31374] ProxyStreamPartitioner should implement ConfigurableStreamPartitioner

- flink-ml-core/src/main/java/org/apache/flink/ml/common/datastream/DataStreamUtils.java
- flink-ml-core/src/main/java/org/apache/flink/ml/common/datastream/sort/BytesKeyNormalizationUtil.java
- flink-ml-core/src/main/java/org/apache/flink/ml/common/datastream/sort/CoGroupOperator.java
- flink-ml-core/src/main/java/org/apache/flink/ml/common/datastream/sort/FixedLengthByteKeyComparator.java
- flink-ml-core/src/main/java/org/apache/flink/ml/common/datastream/sort/KeyAndValueSerializer.java
- flink-ml-core/src/main/java/org/apache/flink/ml/common/datastream/sort/VariableLengthByteKeyComparator.java
- flink-ml-core/src/test/java/org/apache/flink/ml/common/datastream/DataStreamUtilsTest.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/clustering/kmeans/KMeans.java
Add util methods that allow algorithm developers to co-group two DataStreams with the same semantics and similar performance as `DataSet#coGroup(...)`
Here are the results of running the benchmark specified in FLINK-31753's JIRA description:
- DataSet#coGroup takes 27.6 seconds.
- DataStreamUtils#coGroup takes  31.5 seconds.
The DataStream is roughly 12.3% slower than DataSet. The performance difference should be negligible for real-word applications whose co-group function is non-trivial.
Notes: 
- The benchmark is run with Flink 1.18 snapshot.
- Most classes under the `sort` folder are copied from the corresponding classes in apache/flink. We can remove these classese from apache/flink-ml after making the corresponding classes in apache/flink public.
Added the static method …
> [FLINK-31753] Support DataStream CoGroup in stream mode with similar performance as DataSet CoGroup

- flink-ml-python/pyflink/ml/tests/test_ml_lib_completeness.py
For the non-release branch (e.g. master), `mvn package` will generate a jar file named like `flink-ml-lib-2.2-SNAPSHOT.jar`. For release branch, the Flink ML version in pom.xml will no longer include `snapshot` and the jar file will be named like `flink-ml-lib-2.2.jar`. And the method `MLLibTest#_load_java_stages` will fail due to this change.
This PR updates the pattern-matching logic in `MLLibTest#_load_java_stages` so that it will work with both release and non-release branches.
Updated the pattern-matching logic in `MLLibTest#_load_java_stages`
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`:  no
- If yes, how is the feature documented? not …
> [hotfix] Update pattern matching in test_ml_lib_completeness to work with release branch

- flink-ml-iteration/src/main/java/org/apache/flink/iteration/Iterations.java
- flink-ml-iteration/src/main/java/org/apache/flink/iteration/operator/InputOperator.java
This PR proposes to discard watermarks when feeding a datastream into iteration body since watermarks are not correctly processed in iteration module. (See https://issues.apache.org/jira/browse/FLINK-31373)
To avoid the possible bugs, we plan to add a java doc to explain that `flink-m-iteration` module cannot deal with watermarks for now. We also leave it as a TODO here and plan to support it in the future.
- Added a java doc to explain that iterations cannot deal with watermarks correctly.
- Removed watermarks for all datastreams that are fed into a iteration body.
- If yes, how is the …
> [hotfix] Discard watermarks when feed a datastream into iteration body

- flink-ml-iteration/src/main/java/org/apache/flink/iteration/operator/allround/AbstractAllRoundWrapperOperator.java
- flink-ml-iteration/src/main/java/org/apache/flink/iteration/operator/allround/MultipleInputAllRoundWrapperOperator.java
- flink-ml-iteration/src/main/java/org/apache/flink/iteration/operator/allround/OneInputAllRoundWrapperOperator.java
- flink-ml-iteration/src/main/java/org/apache/flink/iteration/operator/allround/TwoInputAllRoundWrapperOperator.java
- flink-ml-tests/src/test/java/org/apache/flink/test/iteration/BoundedAllRoundStreamIterationITCase.java
Fix NPE thrown in ProxyOutput
- Fix NPE thrown in ProxyOutput.
> [FLINK-31373] Fix NPE thrown in ProxyOutput

- .github/workflows/python-tests.yml
- docs/content/docs/try-flink-ml/java/quick-start.md
- docs/content/docs/try-flink-ml/python/quick-start.md
- flink-ml-benchmark/README.md
- flink-ml-iteration/src/main/java/org/apache/flink/iteration/broadcast/BroadcastOutputFactory.java
- flink-ml-iteration/src/main/java/org/apache/flink/iteration/broadcast/OutputReflectionContext.java
- flink-ml-iteration/src/main/java/org/apache/flink/iteration/utils/ReflectionUtils.java
- flink-ml-python/README.md
- flink-ml-python/dev/dev-requirements.txt
- flink-ml-python/pyflink/ml/wrapper.py
- flink-ml-python/setup.py
- pom.xml
Upgrade Flink version of Flink ML to 1.17.0.
Upgrade Flink version of Flink ML to 1.17.0. The main changes about compatibility are sd below.
- 1.17 introduces `CountingOutput` which is used to update metrics, we need to adapt to it.
- 1.17 upgrades the version of Py4j to 0.10.9.7, which introduces a [bug](https://github.com/py4j/py4j/issues/506), we have to change the way to call Java methods in Python temporarily.
> [FLINK-31899] Upgrade Flink version of Flink ML to 1.17.0

- docs/content/docs/try-flink-ml/java/quick-start.md
- docs/content/docs/try-flink-ml/python/quick-start.md
Update the quickstart to require a given Flink version. This is because we can not guarantee that a given Flink ML version can work with multiple Flink versions.
- Updated the quickstart to require Flink 1.17 rather than "Flink 1.17 or higher versions".
- Added instruction to stop Flink cluster in the quickstart.
- If yes, how is the feature documented? JavaDocs
> [hotfix] Update quickstart to require a given Flink version

- pom.xml
Upgrade dependency to fix security vulnerabilities.
- Upgraded jackson.version to 2.13.4 for consistency with Flink. Versions below 2.12.7.1 has known security vulnerabilities according to CVE-2022-42004 and CVE-2022-42003.
- Upgraded com.puppycrawl.tools version to 8.18 because versions below 8.18 has known security vulnerabilities according to CVE-2019-9658 and CVE-2019-10782.
- Upgraded hadoop.version to 2.10.2 for consistency with Flink.
- Updated maven-enforcer-plugin configurations for consistency with Flink.
- Dependencies (does it add or upgrade a dependency): yes
> [hotfix] Upgrade dependency to fix security vulnerabilities

- flink-ml-core/src/main/java/org/apache/flink/ml/common/datastream/TableUtils.java
- flink-ml-core/src/test/java/org/apache/flink/ml/common/datastream/TableUtilsTest.java
Fix TableUtils.getRowTypeInfo when the input contains Tuple.
- Uses `ExternalTypeInfo.of(..)` when the input contains Tuples.
- Adds unit test to cover the fix.
> [FLINK-32292] Fix TableUtils.getRowTypeInfo when the input contains Tuple

- docs/content/docs/try-flink-ml/java/quick-start.md
- docs/content/docs/try-flink-ml/python/quick-start.md
Prior to this PR, the quick-starts will not work for both Java and Python quick-starts because Flink library jars are not correctly loaded. This PR fixes the issue.
Fixed Python and Java quick-starts.
> [hotfix] Update quick-start.md to correctly install Flink ML library jars

- flink-ml-iteration/flink-ml-iteration-common/src/main/java/org/apache/flink/iteration/operator/HeadOperator.java
Fix the ConcurrentModificationException in the unittest.
- Operate the `PipelinedSubpartition#buffers` with lock obtained.
> [FLINK-32335] Fix the ConcurrentModificationException in the unittest

- flink-ml-lib/src/main/java/org/apache/flink/ml/evaluation/binaryclassification/BinaryClassificationEvaluator.java
- flink-ml-lib/src/test/java/org/apache/flink/ml/evaluation/BinaryClassificationEvaluatorTest.java
- flink-ml-python/pyflink/ml/evaluation/tests/tests_binaryclassification.py
Right now, BinaryClassificationEvaluator gives wrong areaUnderROC (auROC) and areaUnderPRC (auPRC) values when a weight column provided. This PR provides fix for their calculation.
- Correct the expected values in the weighted case in BinaryClassificationEvaluatorTest. 
- Correct the calculation of weighted auROC and auPRC. 
- Dependencies (does it add or upgrade a dependency): (yes / no) no
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no) no
- Does this pull request introduce a new feature? (yes / no) no
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) not applicable
> [FLINK-32889] Fix calcuation of weighted areaUnderROC and areaUnderPRC in BinaryClassificationEvaluator

- flink-ml-core/src/main/java/org/apache/flink/ml/common/datastream/DataStreamUtils.java
- flink-ml-core/src/test/java/org/apache/flink/iteration/datacache/nonkeyed/ListStateWithCacheTest.java
- flink-ml-iteration/flink-ml-iteration-common/src/main/java/org/apache/flink/iteration/datacache/nonkeyed/ListStateWithCache.java
- flink-ml-iteration/flink-ml-iteration-common/src/main/java/org/apache/flink/iteration/datacache/nonkeyed/OperatorScopeManagedMemoryManager.java
- flink-ml-iteration/flink-ml-iteration-common/src/test/java/org/apache/flink/iteration/datacache/nonkeyed/OperatorScopeManagedMemoryManagerTest.java
- flink-ml-lib/src/main/java/org/apache/flink/ml/clustering/kmeans/KMeans.java
Right now, by default, an instance of `ListStateWithCache` uses up all the operator-scope managed memory.
It could bring some bugs in some situations, for example, when there exist more than one `ListStateWithCache`s in a single operator, or there are other places using operator-scope managed memory.
This PR tries to fix bugs with such default behaviors.
- Adds `OperatorScopeManagedMemoryManager` to manage all usages of operator-scope managed memory in one operator. Every usage must register itself to the manager, then obtain the sub-fraction of memory it can use.
- Update the constructor of `ListStateWithCache` to get sub-fraction of operator-scope managed memory from an instance of `OperatorScopeManagedMemoryManager`.
- Adds unit tests for validation of the changes.
- Dependencies (does …
> [FLINK-32810] Improve memory allocation in ListStateWithCache

- flink-ml-iteration/flink-ml-iteration-common/src/main/java/org/apache/flink/iteration/operator/allround/MultipleInputAllRoundWrapperOperator.java
- flink-ml-iteration/flink-ml-iteration-common/src/main/java/org/apache/flink/iteration/operator/allround/TwoInputAllRoundWrapperOperator.java
- flink-ml-iteration/flink-ml-iteration-common/src/main/java/org/apache/flink/iteration/operator/perround/MultipleInputPerRoundWrapperOperator.java
- flink-ml-iteration/flink-ml-iteration-common/src/test/java/org/apache/flink/iteration/operator/allround/MultipleInputAllRoundWrapperOperatorTest.java
- flink-ml-iteration/flink-ml-iteration-common/src/test/java/org/apache/flink/iteration/operator/allround/OneInputAllRoundWrapperOperatorTest.java
- flink-ml-iteration/flink-ml-iteration-common/src/test/java/org/apache/flink/iteration/operator/allround/TwoInputAllRoundWrapperOperatorTest.java
- flink-ml-iteration/flink-ml-iteration-common/src/test/java/org/apache/flink/iteration/operator/perround/MultipleInputPerRoundWrapperOperatorTest.java
- flink-ml-iteration/flink-ml-iteration-common/src/test/java/org/apache/flink/iteration/operator/perround/OneInputPerRoundWrapperOperatorTest.java
- flink-ml-iteration/flink-ml-iteration-common/src/test/java/org/apache/flink/iteration/operator/perround/TwoInputPerRoundWrapperOperatorTest.java
This PR fixes a bug in the iteration logic, where the input record was not unwrapped from the IterationRecord before setKeyContext() methods.
- Unwrap data from IterationRecord before invoking setKeyContext() methods in iteration body
> [FLINK-35066] Fix the unwrap from IterationRecord during keyBy
